In [1]:
# 붓꽃 데이터 로드 function
from sklearn.datasets import load_iris
# 분류 알고리즘 
from sklearn.tree import DecisionTreeClassifier
# 학습데이터, 테스트데이터 분리하는 함수 
from sklearn.model_selection import train_test_split

In [2]:
import numpy as np
import pandas as pd

In [3]:
# 붓꽃 데이터 세트를 로딩
iris = load_iris()
type(iris)

sklearn.utils.Bunch

In [4]:
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [5]:
# iris이 데이터 추출
iris_data = iris.data

In [6]:
iris_data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [7]:
# iris.target key : 레이블(답) 데이터 추출
iris_label = iris.target
iris_label

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [8]:
# 품종명 추출
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [9]:
# 추출한 데이터 -> 데이터프레임 생성
iris_df = pd.DataFrame(
      data=iris_data
)
iris_df.head(3)

0    1    2    3
0  5.1  3.5  1.4  0.2
1  4.9  3.0  1.4  0.2
2  4.7  3.2  1.3  0.2

In [10]:
# 추출한 데이터 -> 데이터프레임 생성
iris_df = pd.DataFrame(
      data=iris_data
    , columns=iris.feature_names # 컬럼명
)
iris_df.head(3)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2

In [11]:
# 레이블(답) 추가
iris_df['label'] = iris.target
iris_df.head(3)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   

   label  
0      0  
1      0  
2      0

In [12]:
# 전체 데이터 : 150개
# 학습 데이터 : 120개, 테스트 데이터 : 30개(0.2) 분리
# 학습 레이블 : 120개, 테스트 레이블 : 30개 분리
# 학습데이터 , 테스트데이터, 학습답, 테스트답
X_train    , X_test,       y_train, y_test= train_test_split(
      iris_data # 분리할 데이터
    , iris_label # 분리할 답
    , test_size=0.2 # 테스트데이터의 크기 지정
    , random_state=11 # random_seed 동일
)

In [13]:
# 학습시 사용될 학습데이터, 학습 답
X_train, y_train

(array([[5.1, 3.5, 1.4, 0.2],
        [6.9, 3.2, 5.7, 2.3],
        [7.7, 2.8, 6.7, 2. ],
        [5. , 3.3, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [7.7, 2.6, 6.9, 2.3],
        [7.6, 3. , 6.6, 2.1],
        [6.7, 3. , 5. , 1.7],
        [5.5, 3.5, 1.3, 0.2],
        [6. , 2.7, 5.1, 1.6],
        [5. , 2. , 3.5, 1. ],
        [7.9, 3.8, 6.4, 2. ],
        [4.6, 3.4, 1.4, 0.3],
        [6.9, 3.1, 4.9, 1.5],
        [6.5, 3. , 5.8, 2.2],
        [5.1, 2.5, 3. , 1.1],
        [6.6, 2.9, 4.6, 1.3],
        [5. , 3.2, 1.2, 0.2],
        [7.4, 2.8, 6.1, 1.9],
        [5.1, 3.8, 1.6, 0.2],
        [6.8, 3.2, 5.9, 2.3],
        [6.9, 3.1, 5.1, 2.3],
        [5.9, 3. , 4.2, 1.5],
        [4.9, 2.5, 4.5, 1.7],
        [6.7, 3.1, 4.7, 1.5],
        [4.4, 3.2, 1.3, 0.2],
        [5.4, 3.4, 1.7, 0.2],
        [6.5, 2.8, 4.6, 1.5],
        [5.1, 3.7, 1.5, 0.4],
        [5. , 3.4, 1.6, 0.4],
        [6.1, 2.6, 5.6, 1.4],
        [6.5, 3. , 5.5, 1.8],
        [6.3, 2.5, 5. , 1.9],
        [5

In [14]:
# 테스트시 사용될 데스트데이터, 테스트 답
X_test, y_test

(array([[6.8, 3. , 5.5, 2.1],
        [6.7, 3. , 5.2, 2.3],
        [6.3, 2.8, 5.1, 1.5],
        [6.3, 3.3, 4.7, 1.6],
        [6.4, 2.7, 5.3, 1.9],
        [4.9, 3.1, 1.5, 0.1],
        [6.7, 3.1, 4.4, 1.4],
        [5.7, 4.4, 1.5, 0.4],
        [4.8, 3.1, 1.6, 0.2],
        [6.1, 2.9, 4.7, 1.4],
        [6. , 2.2, 5. , 1.5],
        [6. , 2.2, 4. , 1. ],
        [5.4, 3. , 4.5, 1.5],
        [5.7, 2.5, 5. , 2. ],
        [6.9, 3.1, 5.4, 2.1],
        [4.5, 2.3, 1.3, 0.3],
        [6.3, 2.9, 5.6, 1.8],
        [5.6, 3. , 4.5, 1.5],
        [6.5, 3.2, 5.1, 2. ],
        [5.8, 2.7, 5.1, 1.9],
        [5.6, 2.5, 3.9, 1.1],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.6, 1. , 0.2],
        [6.4, 3.2, 4.5, 1.5],
        [4.8, 3. , 1.4, 0.1],
        [4.8, 3.4, 1.6, 0.2],
        [5.9, 3. , 5.1, 1.8],
        [6.6, 3. , 4.4, 1.4],
        [5.4, 3.9, 1.3, 0.4],
        [6. , 3.4, 4.5, 1.6]]),
 array([2, 2, 2, 1, 2, 0, 1, 0, 0, 1, 2, 1, 1, 2, 2, 0, 2, 1, 2, 2, 1, 0,
        0, 1, 0, 0, 2, 1

In [15]:
# 모델 : 학습데이터와 학습답으로 학습한 결과
# 분류로 학습 진행
# DecisionTreeClassifier : 분류 처리 객체만 생성 -> 학습X
dt_clf = DecisionTreeClassifier(random_state=11)
dt_clf

DecisionTreeClassifier(random_state=11)

In [16]:
# 학습데이터(X_train), 답(y_train)을 넣어서 학습 수행
dt_clf.fit(X_train, y_train)
# dt_clf라는 객체안에 모델(학습결과 : 식) 생성

DecisionTreeClassifier(random_state=11)

In [17]:
# 테스트데이터(X_test)를 모델 넣어서 예측 결과 반환
pred = dt_clf.predict(X_test)
pred

array([2, 2, 1, 1, 2, 0, 1, 0, 0, 1, 1, 1, 1, 2, 2, 0, 2, 1, 2, 2, 1, 0,
       0, 1, 0, 0, 2, 1, 0, 1])

In [18]:
# 0번째 테스트데이터, 예측값,     원래값
X_test[0],            pred[0],    y_test[0]

(array([6.8, 3. , 5.5, 2.1]), 2, 2)

In [19]:
pred == y_test

array([ True,  True, False,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [20]:
np.sum(pred == y_test)

28

In [21]:
# 정확도 계산

28/30 * 100

93.33333333333333

In [22]:
# accuacy_score : 정확도 계산 함수
# y_test(원래값) == pred(예측결과값)
from sklearn.metrics import accuracy_score
accuracy_score(y_test, pred)

0.9333333333333333

In [23]:
print('예측 정확도 : {0:.4f}'.format(accuracy_score(y_test, pred)))

예측 정확도 : 0.9333


In [24]:
# iris dataset 확인
from sklearn.datasets import load_iris

# iris data 읽기
iris_data = load_iris()

keys = iris_data.keys()

In [25]:
keys

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [26]:
# 컬럼명 추출
iris_data.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [27]:
# 정답 이름 추출
iris_data.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [28]:
# 데이터의 구조 확인
iris_data.data.shape

(150, 4)

In [29]:
# 정답값 : 0, 1, 2 ('setosa', 'versicolor', 'virginica')
iris_data.target.shape

(150,)